[host]
default="http://personal.app.com"

[ticket]
path="/ticket/beta"

[solutions]
path="/solutions/beta"

[contacts]
path="/contacts/beta"

[search]
path="/indexer/v2"

[database]
schema="smartscript"
host="..."
user="..."
pass="..."