[host]
default="http://personal.app.com"

[ticket]
path="/ticket/"

[solutions]
path="/solutions/dev"

[contacts]
path="/contacts/dev"

[search]
path="/indexer/v2"

[database]
schema="smartscript"
host="..."
user="..."
pass="..."